# Scott Breitbach
## 16-March-2021
## DSC550, Week 1

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)

# 1.2 Exercise: Working with Arrays

### 2D Arrays

1) Create an array of size [10,50] and use the random function to fill it with integers between 1 and 500 (inclusive).  

In [2]:
# nrows = 3
# ncols = 2
nrows = 10
ncols = 50
size = nrows * ncols

In [3]:
array = np.random.randint(1, 501, size).reshape(nrows, ncols)
array

array([[103, 436, 349, 271, 107,  72, 189,  21, 103, 122, 467, 215, 331,
        459,  88, 373, 100, 360, 152, 131, 150, 309, 258, 344, 492, 414,
        294, 386, 192, 444, 277, 161, 460, 314,  22, 253, 236, 345,  49,
        475,  59, 170, 476, 188, 464, 271, 190, 446, 175, 446],
       [ 51, 364,  55, 244, 320, 131, 485, 307, 135,  21, 329, 167, 274,
        388,  89, 316,  14, 242, 265, 346,  53, 386, 340,  92, 367, 444,
        455, 428, 264, 431,  35, 206,  81, 420,  50, 360, 388,   2, 390,
         54, 106, 260, 310, 477, 191, 402, 218,  44, 162, 202],
       [446, 484, 270, 351, 304, 271, 456, 462, 215, 252, 190, 296, 213,
        208, 237, 338, 367,  53, 280, 410, 217, 252, 188, 380, 493,  41,
        157,  15, 301,  65, 345, 327,   9, 344, 129, 492, 136, 472,  63,
        139, 499,  81, 392, 163, 419, 289, 379, 261, 490, 231],
       [ 41,  28, 135, 201, 328, 268, 418,  33,  48, 407,  62, 216, 293,
         99, 172, 360, 214, 475,  35, 449, 227, 101, 431, 462, 131, 257,
     

Load it to a DataFrame

In [4]:
df = pd.DataFrame(array)
df

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
0  103  436  349  271  107   72  189   21  103  122  ...   59  170  476  188   
1   51  364   55  244  320  131  485  307  135   21  ...  106  260  310  477   
2  446  484  270  351  304  271  456  462  215  252  ...  499   81  392  163   
3   41   28  135  201  328  268  418   33   48  407  ...   63  352  231  241   
4  231  237  143  171   29   36   13  160  327  187  ...  233  259  359  198   
5  307  234  172  152  463  315  374  160   96  472  ...   53  172  218  160   
6  184  123  401  255  294  280  325  372   98  198  ...  360  129  267  476   
7  298   99  263  252  144  346  112  500   60  369  ...  227  112  473   99   
8  194  310  163  208  445  169  484  161   68  289  ...  286   97  284  367   
9    4   35  192   49   17  172  220  158  477   46  ...   58  323  360  174   

    44   45   46   47   48   49  
0  464  271  190  446  175  446  
1  191  402  218   44  162  202  
2  419  289  379  261  490  231  
3   52   96  388  222  485  407  
4  456  411  137  318  165  225  
5  198  416  247  324  439  203  
6  441  473  434  151  415  478  
7  153  349  402  384  366  338  
8  448  481  453  317  304  147  
9  280  114  288  431  342  151  

[10 rows x 50 columns]

2) Calculate the sum of each row

In [5]:
# print("Sum of Row:")
# df.sum(axis=1)

In [6]:
print("Sum of each row:")
np.sum(array, axis=1)

Sum of each row:


array([13209, 12161, 13872, 11969, 11477, 12221, 14862, 11811, 13638,
       11341])

The sum of each column

In [7]:
# print("Sum of Column:")
# df.sum()

In [8]:
print("Sum of each column:")
np.sum(array, axis=0)

Sum of each column:


array([1859, 2350, 2143, 2154, 2451, 2060, 3076, 2334, 1627, 2363, 2767,
       2223, 2455, 2720, 2107, 2957, 1385, 2730, 2394, 3133, 1724, 1946,
       2373, 2822, 3635, 3093, 2550, 1963, 2640, 2823, 2532, 2080, 2406,
       2950, 2328, 3078, 3043, 2472, 2033, 2361, 1944, 1955, 3370, 2543,
       3102, 3302, 3136, 2898, 3343, 2828])

The sum of all entries

In [9]:
print("Sum of entire matrix:")
np.sum(array)

Sum of entire matrix:


126561

3) Determine the minimum of all entries

In [10]:
print("Smallest number in the matrix:")
np.min(array)

Smallest number in the matrix:


2

Maximum

In [11]:
print("Largest number in the matrix:")
np.max(array)

Largest number in the matrix:


500

Average

In [12]:
print("Average of all entries:")
np.mean(array).round(2)

Average of all entries:


253.12

Standard deviation

In [13]:
np.std(array).round(2)

140.92

4) Sort the Dataframe  
a) sort on column 2

In [14]:
df.sort_values(by=1, axis=0, ascending=True)

0    1    2    3    4    5    6    7    8    9   ...   40   41   42   43  \
3   41   28  135  201  328  268  418   33   48  407  ...   63  352  231  241   
9    4   35  192   49   17  172  220  158  477   46  ...   58  323  360  174   
7  298   99  263  252  144  346  112  500   60  369  ...  227  112  473   99   
6  184  123  401  255  294  280  325  372   98  198  ...  360  129  267  476   
5  307  234  172  152  463  315  374  160   96  472  ...   53  172  218  160   
4  231  237  143  171   29   36   13  160  327  187  ...  233  259  359  198   
8  194  310  163  208  445  169  484  161   68  289  ...  286   97  284  367   
1   51  364   55  244  320  131  485  307  135   21  ...  106  260  310  477   
0  103  436  349  271  107   72  189   21  103  122  ...   59  170  476  188   
2  446  484  270  351  304  271  456  462  215  252  ...  499   81  392  163   

    44   45   46   47   48   49  
3   52   96  388  222  485  407  
9  280  114  288  431  342  151  
7  153  349  402  384  366  338  
6  441  473  434  151  415  478  
5  198  416  247  324  439  203  
4  456  411  137  318  165  225  
8  448  481  453  317  304  147  
1  191  402  218   44  162  202  
0  464  271  190  446  175  446  
2  419  289  379  261  490  231  

[10 rows x 50 columns]

b) sort on row 2

In [15]:
df.sort_values(by=1, axis=1, ascending=True)

37   16   9    30   47   34   0    20   39   2   ...   13   38   45   33  \
0  345  100  122  277  446   22  103  150  475  349  ...  459   49  271  314   
1    2   14   21   35   44   50   51   53   54   55  ...  388  390  402  420   
2  472  367  252  345  261  129  446  217  139  270  ...  208   63  289  344   
3  380  214  407  359  222   15   41  227  179  135  ...   99  461   96  207   
4  121   62  187  231  318  377  231   28  461  143  ...   66  116  411  385   
5  403   52  472  220  324  224  307  387  130  172  ...  318  126  416  485   
6  128  124  198  148  151  489  184  349  338  401  ...  144   39  473  308   
7  104   37  369  408  384  456  298   99  254  263  ...  254  340  349  113   
8   27  135  289   38  317  438  194   33  277  163  ...  404  226  481   51   
9  490  280   46  471  431  128    4  181   54  192  ...  380  223  114  323   

    27   29   25   26   43   6   
0  386  444  414  294  188  189  
1  428  431  444  455  477  485  
2   15   65   41  157  163  456  
3  218  398  257    5  241  418  
4  128  473  446  331  198   13  
5  113  130   81  187  160  374  
6  346  147  420  403  476  325  
7   54  161  404  152   99  112  
8   22  158  470  375  367  484  
9  253  416  116  191  174  220  

[10 rows x 50 columns]