# Chapter 1: Vectors, Matrices, and Arrays

In [1]:
import numpy as np
from scipy import sparse

## 1.1 Creating a Vector

Create a vector as a row

In [2]:
vectorRow = np.array([1,2,3])

In [4]:
vectorRow

array([1, 2, 3])

Create a vector as a column

In [3]:
vectorCol = np.array([[1],
                      [2],
                      [3]])

In [5]:
vectorCol

array([[1],
       [2],
       [3]])

## 1.2 Creating a Matrix

Create a matrix:

In [7]:
matrix = np.array([[1,2],
                  [1,2],
                  [1,2]])

In [8]:
matrix

array([[1, 2],
       [1, 2],
       [1, 2]])

NumPy has a dediated matrix data structure:

In [9]:
matrixObject = np.matrix([[1,2],
                          [1,2],
                          [1,2]])

In [10]:
matrixObject

matrix([[1, 2],
        [1, 2],
        [1, 2]])

## 1.3 Creating a Sparse Matrix

In [11]:
from scipy import sparse

Create a matrix:

In [12]:
matrix = np.array([[0,0],
                  [0,1],
                  [3,0]])

Create a compressed sparse row (CSR) matrix:

In [13]:
matrixSparse = sparse.csr_matrix(matrix)

In [14]:
matrixSparse

<3x2 sparse matrix of type '<class 'numpy.intc'>'
	with 2 stored elements in Compressed Sparse Row format>

In [15]:
print(matrixSparse)

  (1, 1)	1
  (2, 0)	3


Create a larger matrix:

In [16]:
matrixLarge = np.array([[0,0,0,0,0,0,0,0,0,0],
                        [0,1,0,0,0,0,0,0,0,0],
                        [3,0,0,0,0,0,0,0,0,0]])

Create CSR matrix:

In [17]:
matrixLargeSparse = sparse.csr_matrix(matrixLarge)

In [18]:
print(matrixLargeSparse)

  (1, 1)	1
  (2, 0)	3


## 1.4 Selecting Elements

Create a row vector:

In [19]:
vector = np.array([1,2,3,4,5,6])

Create matrix:

In [20]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

Select third element of the vector:

In [21]:
vector[2]

3

Select the second row, second column of the matrix:

In [23]:
matrix[1,1]

5

Many options for selecting elements or groups of elements in arrays:

In [25]:
vector[:]

array([1, 2, 3, 4, 5, 6])

In [26]:
vector[:3]

array([1, 2, 3])

In [27]:
vector[3:]

array([4, 5, 6])

In [28]:
vector[-1]

6

In [29]:
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

## 1.5 Describing a Matrix

In [31]:
matrix = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10, 11, 12]])

View the number of rows and columns:

In [32]:
matrix.shape

(3, 4)

View the number of elements:

In [33]:
matrix.size

12

View the number of dimensions:

In [34]:
matrix.ndim

2

## 1.6 Applying Operations to Elements

In [35]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

Create a function that adds 100 to something:

In [36]:
add100 = lambda i: i + 100

Create a vectorized function:

In [37]:
vectorizedAdd100 = np.vectorize(add100)

Apply function to all elements in matrix:

In [38]:
vectorizedAdd100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

Create a simpler version using *broadcasting*:

In [39]:
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 1.7 Finding the Maximum and Minimum Values

In [35]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [40]:
np.max(matrix)

9

In [41]:
np.min(matrix)

1

Find max in each column:

In [42]:
np.max(matrix, axis=0)

array([7, 8, 9])

Find max in each row:

In [43]:
np.max(matrix, axis=1)

array([3, 6, 9])

## 1.8 Calculating the Average, Variance, and Standard Deviation

In [35]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [44]:
np.mean(matrix)

5.0

In [45]:
np.var(matrix)

6.666666666666667

In [46]:
np.std(matrix)

2.581988897471611

Can also use these along an axis:

In [47]:
np.mean(matrix, axis=0)

array([4., 5., 6.])

## 1.9 Reshaping Arrays

Create a 4x3 matrix:

In [49]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [10, 11, 12]])

Reshape to a 2x6 matrix:

In [50]:
matrix.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

Use **-1** for "as many as needed":

In [51]:
matrix.reshape(1,-1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [52]:
matrix.reshape(12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
matrix.reshape(-1)

## 1.10 Transposing a Vector or Matrix

In [53]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

Transpose the matrix:

In [54]:
matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Technically you cannot transpose a vector, but you can convert from a row vector to a column vector:

In [55]:
np.array([1,2,3,4,5,6]).T

array([1, 2, 3, 4, 5, 6])

In [56]:
np.array([[1,2,3,4,5,6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## 1.11 Flattening a Matrix

In [35]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [57]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Can do the same thing with `.reshape()` from above

## 1.12 Finding the Rank of a Matrix

In [59]:
matrix = np.array([[1,1,1],
                  [1,1,10],
                  [1,1,15]])

Return the matrix rank:

In [60]:
np.linalg.matrix_rank(matrix)

2

## 1.13 Calculating the Determinant

In [63]:
matrix = np.array([[1,2,3],
                  [2,4,6],
                  [3,8,9]])

Return the determinant of the matrix:

In [64]:
np.linalg.det(matrix)

0.0

## 1.14 Getting the Diagonal of a Matrix

In [65]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

Use `diagonal()`:

In [66]:
matrix.diagonal()

array([1, 5, 9])

Use `offset=` to get the diagonal offset from the main diagonal:

In [67]:
matrix.diagonal(offset=1)

array([2, 6])

In [68]:
matrix.diagonal(offset=-1)

array([4, 8])

## 1.15 Calculating the Trace of a Matrix

In [72]:
matrix = np.array([[1,2,3],
                  [2,4,6],
                  [3,8,9]])

In [73]:
matrix.trace()

14

In [74]:
sum(matrix.diagonal())

14

## 1.16 Finding Eigenvalues and Eigenvectors

In [75]:
matrix = np.array([[1,-1,3],
                  [1,1,6],
                  [3,8,9]])

In [76]:
eigenvalues, eigenvectors = np.linalg.eig(matrix)

In [77]:
eigenvalues

array([13.55075847,  0.74003145, -3.29078992])

In [78]:
eigenvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 1.17 Calculating Dot Products

In [79]:
vectorA = np.array([1,2,3])
vectorB = np.array([4,5,6])

In [80]:
np.dot(vectorA, vectorB)

32

## 1.18 Adding and Subtracting Matrices

In [81]:
matrixA = np.array([[1,1,1],
                   [1,1,1],
                   [1,1,2]])

In [82]:
matrixB = np.array([[1,3,1],
                   [1,3,1],
                   [1,3,8]])

In [83]:
np.add(matrixA, matrixB)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [84]:
np.subtract(matrixA, matrixB)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [85]:
matrixA + matrixB

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

## 1.19 Multiplying Matrices

In [86]:
matrixA = np.array([[1,1],
                   [1,2]])

In [87]:
matrixB = np.array([[1,3],
                   [1,2]])

In [88]:
np.dot(matrixA,matrixB)

array([[2, 5],
       [3, 7]])

Can also use the `@` operator:

In [89]:
matrixA @ matrixB

array([[2, 5],
       [3, 7]])

Use `*` to do element-wise multiplication:

In [90]:
matrixA * matrixB

array([[1, 3],
       [1, 4]])

## 1.20 Inverting a Matrix

In [91]:
matrix = ([[1,4],
          [2,5]])

In [92]:
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

## 1.21 Generating Random Values

In [93]:
# Can set a seed to get the same random numbers repeatedly:
np.random.seed(42)

Generate floats:

In [94]:
np.random.random(3)

array([0.37454012, 0.95071431, 0.73199394])

Generate 3 random integers between 0 and 10:

In [95]:
np.random.randint(0, 11, 3)

array([4, 6, 9])

Generate numbers by drawing them from a distribution:

In [98]:
# Draw three numbers from a normal distribution with mean 0.0 and std 1.0:
np.random.normal(0.0, 1.0, 3)

array([-0.52516981, -0.57138017, -0.92408284])

In [99]:
# Draw three numbers from a log distribution with mean 0.0 and scale of 1.0:
np.random.logistic(0.0, 1.0, 3)

array([ 0.09910677, -0.2739199 , -0.88942191])

In [101]:
# Draw three numbers >= 1.0 and < 2.0:
np.random.uniform(1.0, 2.0, 3)

array([1.61185289, 1.13949386, 1.29214465])