In [1]:
import pandas as pd

In [126]:
commentsDF = pd.read_json("controversial-comments\controversial-comments.jsonl", lines=True)

In [9]:
# testDF = pd.DataFrame()

In [10]:
# testDF['txt'] = commentsDF['txt'].str.lower()

In [11]:
# testDF.head()

In [127]:
commentsDF = commentsDF.sample(100)

In [128]:
saveDF = commentsDF.copy()

### Make lowercase

In [129]:
commentsDF.txt = commentsDF['txt'].str.lower()

In [130]:
commentsDF.head()

con                                                txt
90730     0  because specifically black-on-black homicide i...
616522    0  when i watched the second debate, all i heard ...
790246    0                        op, trump is a russian tool
21463     0  don't quit your day job. comedy just isn't for...
291574    0  &gt;privco, which provides financial and busin...

In [16]:
commentsDF.con.unique()

array([0, 1], dtype=int64)

### Remove Punctuation

In [18]:
import unicodedata
import sys

In [106]:
punctuation = dict.fromkeys(i for i in range(sys.maxunicode) 
                            if unicodedata.category(chr(i)).startswith('P'))

In [107]:
testDF = commentsDF.copy()

In [25]:
test = [string.translate(punctuation) for string in testDF.txt]

In [26]:
type(test)

list

In [27]:
len(test)

950000

In [28]:
len(testDF)

950000

In [108]:
testDF.txt = [string.translate(punctuation) for string in testDF.txt]

In [109]:
testDF.head()

con                                                txt
813846    0        what an absolute fucking moron unbelievable
923674    0  you made me laugh on a very bleak news day tha...
76991     0    not every word has to he capitalised in a title
174968    0                                   thats even worse
442606    0  listen keep that realism to yourself no one wa...

In [131]:
commentsDF.txt = [string.translate(punctuation) for string in commentsDF.txt]

In [110]:
commentsDF = testDF.copy()

### Remove Stop Words

In [32]:
from nltk.corpus import stopwords

In [33]:
# import nltk

In [35]:
# nltk.download('stopwords')

In [36]:
stop_words = stopwords.words('english')

#### Remove stop words

In [43]:
[word for word in tokenized_words if word not in stop_words]

['going', 'go', 'store', 'park']

In [38]:
testDF.txt.iloc[0]

'well its great that he did something about those beliefs while he was in office i doubt trump would fight the un for it so im really really happy obama did something while he couldoh wait'

In [40]:
type(testDF.txt.iloc[0])

str

In [42]:
from nltk.tokenize import word_tokenize

In [43]:
string = testDF.txt.iloc[0]

In [47]:
tokenized_words = word_tokenize(string)

In [48]:
len(tokenized_words)

36

In [51]:
noStops = [word for word in tokenized_words if word not in stop_words]

In [59]:
# noStops

In [53]:
len(noStops)

18

In [57]:
def removeStopWords(string):
    tokenized_words = word_tokenize(string)
    return [word for word in tokenized_words if word not in stop_words]

In [55]:
string

'well its great that he did something about those beliefs while he was in office i doubt trump would fight the un for it so im really really happy obama did something while he couldoh wait'

In [58]:
removeStopWords(string)

['well',
 'great',
 'something',
 'beliefs',
 'office',
 'doubt',
 'trump',
 'would',
 'fight',
 'un',
 'im',
 'really',
 'really',
 'happy',
 'obama',
 'something',
 'couldoh',
 'wait']

In [60]:
testDF.head()

con                                                txt
0    0  well its great that he did something about tho...
1    0                         you are right mr president
2    0  you have given no input apart from saying i am...
3    0  i get the frustration but the reason they want...
4    0  i am far from an expert on tpp and i would ten...

In [111]:
testDF.txt.apply(lambda x: removeStopWords(x))

813846             [absolute, fucking, moron, unbelievable]
923674    [made, laugh, bleak, news, day, thank, kind, s...
76991                     [every, word, capitalised, title]
174968                                 [thats, even, worse]
442606      [listen, keep, realism, one, wants, hear, shit]
                                ...                        
864267    [would, better, dismantle, deep, state, everyo...
24377     [oh, yeah, dont, mean, say, hes, completely, p...
414327    [im, bergers, district, unopposed, democrats, ...
888733    [youve, showed, dont, understand, google, even...
886803                         [neither, shut, fuck, guess]
Name: txt, Length: 100, dtype: object

In [112]:
testDF.head()

con                                                txt
813846    0        what an absolute fucking moron unbelievable
923674    0  you made me laugh on a very bleak news day tha...
76991     0    not every word has to he capitalised in a title
174968    0                                   thats even worse
442606    0  listen keep that realism to yourself no one wa...

In [63]:
len(testDF.txt.iloc[0])

187

In [64]:
len(commentsDF.txt.iloc[0])

187

In [66]:
len(commentsDF)

950000

In [95]:
commentsDF = commentsDF.sample(10000)

In [70]:
len(commentsDF)

10000

In [132]:
commentsDF.txt = commentsDF.txt.apply(lambda x: removeStopWords(x))

In [133]:
saveDF = commentsDF.copy()

In [134]:
commentsDF.head()

con                                                txt
90730     0  [specifically, blackonblack, homicide, complet...
616522    0   [watched, second, debate, heard, baldwin, trump]
790246    0                         [op, trump, russian, tool]
21463     0               [dont, quit, day, job, comedy, isnt]
291574    0  [gtprivco, provides, financial, business, data...

In [73]:
len(commentsDF.txt.iloc[0])

43

### Apply PorterStemmer

In [74]:
from nltk.stem.porter import PorterStemmer

In [75]:
porter = PorterStemmer()

In [51]:
[porter.stem(word) for word in tokenized_words]

['i', 'am', 'humbl', 'by', 'thi', 'tradit', 'meet']

In [79]:
[porter.stem(word) for word in commentsDF.txt.iloc[0]][:5]

['good', 'chanc', 'two', 'parti', 'go']

In [135]:
commentsDF.head()

con                                                txt
90730     0  [specifically, blackonblack, homicide, complet...
616522    0   [watched, second, debate, heard, baldwin, trump]
790246    0                         [op, trump, russian, tool]
21463     0               [dont, quit, day, job, comedy, isnt]
291574    0  [gtprivco, provides, financial, business, data...

In [136]:
testDF = commentsDF[:10].copy()

In [137]:
testDF.head()

con                                                txt
90730     0  [specifically, blackonblack, homicide, complet...
616522    0   [watched, second, debate, heard, baldwin, trump]
790246    0                         [op, trump, russian, tool]
21463     0               [dont, quit, day, job, comedy, isnt]
291574    0  [gtprivco, provides, financial, business, data...

In [138]:
testDF.txt.apply(lambda x: [porter.stem(word) for word in x])

90730     [specif, blackonblack, homicid, complet, contr...
616522        [watch, second, debat, heard, baldwin, trump]
790246                           [op, trump, russian, tool]
21463                  [dont, quit, day, job, comedi, isnt]
291574    [gtprivco, provid, financi, busi, data, major,...
653580                              [right, wikileak, back]
695602    [explain, think, harri, potter, satan, recruit...
11663                                               [remov]
58065     [would, give, essenti, liberti, purchas, littl...
78815                                               [delet]
Name: txt, dtype: object

In [140]:
testDF.txt = testDF.txt.apply(lambda x: [porter.stem(word) for word in x])

In [141]:
testDF.head()

con                                                txt
90730     0  [specif, blackonblack, homicid, complet, contr...
616522    0      [watch, second, debat, heard, baldwin, trump]
790246    0                         [op, trump, russian, tool]
21463     0               [dont, quit, day, job, comedi, isnt]
291574    0  [gtprivco, provid, financi, busi, data, major,...

In [142]:
commentsDF.txt = commentsDF.txt.apply(lambda x: [porter.stem(word) for word in x])

In [143]:
commentsDF.head()

con                                                txt
90730     0  [specif, blackonblack, homicid, complet, contr...
616522    0      [watch, second, debat, heard, baldwin, trump]
790246    0                         [op, trump, russian, tool]
21463     0               [dont, quit, day, job, comedi, isnt]
291574    0  [gtprivco, provid, financi, busi, data, major,...

In [144]:
saveDF = commentsDF.copy()

In [145]:
len(saveDF)

100

In [185]:
testDF = commentsDF[:10].copy()

In [186]:
len(testDF)

10

In [187]:
testDF.head()

con                                                txt
90730     0  [specif, blackonblack, homicid, complet, contr...
616522    0      [watch, second, debat, heard, baldwin, trump]
790246    0                         [op, trump, russian, tool]
21463     0               [dont, quit, day, job, comedi, isnt]
291574    0  [gtprivco, provid, financi, busi, data, major,...

In [153]:
type(testDF.txt)

pandas.core.series.Series

## 2)

### Convert each text entry into a word-count vector

In [147]:
from sklearn.feature_extraction.text import CountVectorizer

In [148]:
count = CountVectorizer()

In [157]:
text_data = testDF.txt.array

In [179]:
testDF.txt.iloc[0]

['specif',
 'blackonblack',
 'homicid',
 'complet',
 'control',
 'problem',
 'call',
 'problem',
 'commun',
 'violenc',
 'lol',
 'commun']

In [159]:
bagOfWords = count.fit_transform(text_data)

SyntaxError: invalid syntax (<ipython-input-159-cd20df489f38>, line 1)

In [160]:
testDF.txt.array

<PandasArray>
[                                                                                                                                                                                                                                   ['specif', 'blackonblack', 'homicid', 'complet', 'control', 'problem', 'call', 'problem', 'commun', 'violenc', 'lol', 'commun'],
                                                                                                                                                                                                                                                                                                          ['watch', 'second', 'debat', 'heard', 'baldwin', 'trump'],
                                                                                                                                                                                                                                                                                

In [165]:
listOfWords = []

In [166]:
for text in testDF.txt:
    for word in text:
        listOfWords.append(word)

In [168]:
# listOfWords

In [169]:
text_data = listOfWords

In [170]:
bagOfWords = count.fit_transform(text_data)

In [173]:
bagOfWords

<118x103 sparse matrix of type '<class 'numpy.int64'>'
	with 118 stored elements in Compressed Sparse Row format>

In [171]:
bagOfWords.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [174]:
# count.get_feature_names()

In [176]:
pd.DataFrame(bagOfWords.toarray(), columns=count.get_feature_names())

000  10  22450  back  baldwin  believ  blackonblack  busi  call  code  \
0      0   0      0     0        0       0             0     0     0     0   
1      0   0      0     0        0       0             1     0     0     0   
2      0   0      0     0        0       0             0     0     0     0   
3      0   0      0     0        0       0             0     0     0     0   
4      0   0      0     0        0       0             0     0     0     0   
..   ...  ..    ...   ...      ...     ...           ...   ...   ...   ...   
113    0   0      0     0        0       0             0     0     0     0   
114    0   0      0     0        0       0             0     0     0     0   
115    0   0      0     0        0       0             0     0     0     0   
116    0   0      0     0        0       0             0     0     0     0   
117    0   0      0     0        0       0             0     0     0     0   

     ...  trump  violenc  want  watch  wikileak  witchcraft  work  worker  \
0    ...      0        0     0      0         0           0     0       0   
1    ...      0        0     0      0         0           0     0       0   
2    ...      0        0     0      0         0           0     0       0   
3    ...      0        0     0      0         0           0     0       0   
4    ...      0        0     0      0         0           0     0       0   
..   ...    ...      ...   ...    ...       ...         ...   ...     ...   
113  ...      0        0     0      0         0           0     0       0   
114  ...      0        0     0      0         0           0     0       0   
115  ...      0        0     0      0         0           0     0       0   
116  ...      0        0     0      0         0           0     0       0   
117  ...      0        0     0      0         0           0     0       0   

     worldwid  would  
0           0      0  
1           0      0  
2           0      0  
3           0      0  
4           0      0  
..        ...    ...  
113         0      0  
114         0      0  
115         0      0  
116         0      0  
117         0      0  

[118 rows x 103 columns]

#### Okay, let's try this again

In [21]:
count = CountVectorizer()

In [ ]:
text_data = 

In [ ]:
bagOfWords = count.fit_transform(text_data)

In [ ]:
bagOfWords.toarray()

In [188]:
testDF.head()

con                                                txt
90730     0  [specif, blackonblack, homicid, complet, contr...
616522    0      [watch, second, debat, heard, baldwin, trump]
790246    0                         [op, trump, russian, tool]
21463     0               [dont, quit, day, job, comedi, isnt]
291574    0  [gtprivco, provid, financi, busi, data, major,...

In [181]:
testDF.txt.apply(lambda x: count.fit_transform(x).toarray())

90730     [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, ...
616522    [[0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0], [0, 1...
790246    [[1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [0,...
21463     [[0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 1...
291574    [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,...
653580                    [[0, 1, 0], [0, 0, 1], [1, 0, 0]]
695602    [[0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
11663                                                 [[1]]
58065     [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
78815                                                 [[1]]
Name: txt, dtype: object

In [189]:
testDF.txt = testDF.txt.apply(lambda x: count.fit_transform(x).toarray())

In [190]:
testDF.head()

con                                                txt
90730     0  [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, ...
616522    0  [[0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0], [0, 1...
790246    0  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [0,...
21463     0  [[0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 1...
291574    0  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,...

In [191]:
testDF.txt.iloc[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [192]:
commentsDF['WCV'] = commentsDF.txt.apply(lambda x: count.fit_transform(x).toarray())

In [193]:
commentsDF.head()

con                                                txt  \
90730     0  [specif, blackonblack, homicid, complet, contr...   
616522    0      [watch, second, debat, heard, baldwin, trump]   
790246    0                         [op, trump, russian, tool]   
21463     0               [dont, quit, day, job, comedi, isnt]   
291574    0  [gtprivco, provid, financi, busi, data, major,...   

                                                      WCV  
90730   [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, ...  
616522  [[0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0], [0, 1...  
790246  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [0,...  
21463   [[0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 1...  
291574  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,...

In [194]:
saveDF = commentsDF.copy()

In [195]:
testDF = commentsDF[:10].copy()

### Convert each text entry to Part-of-Speech tag vector

In [196]:
from nltk import pos_tag
from nltk import word_tokenize

In [53]:
textData = "Chris loved outdoor running"

In [197]:
# import nltk
# nltk.download('averaged_perceptron_tagger')

In [56]:
textTagged = pos_tag(word_tokenize(textData))

In [57]:
textTagged

[('Chris', 'NNP'), ('loved', 'VBD'), ('outdoor', 'RP'), ('running', 'VBG')]

In [198]:
testDF.txt.iloc[0]

['specif',
 'blackonblack',
 'homicid',
 'complet',
 'control',
 'problem',
 'call',
 'problem',
 'commun',
 'violenc',
 'lol',
 'commun']

In [199]:
listOfWords = testDF.txt.iloc[0]

In [200]:
tag = nltk.pos_tag(listOfWords)

[('specif', 'JJ'),
 ('blackonblack', 'NN'),
 ('homicid', 'JJ'),
 ('complet', 'NN'),
 ('control', 'NN'),
 ('problem', 'NN'),
 ('call', 'NN'),
 ('problem', 'NN'),
 ('commun', 'NN'),
 ('violenc', 'NN'),
 ('lol', 'NN'),
 ('commun', 'NN')]

In [ ]:
tagged = []
tagged

In [201]:
testDF.head()

con                                                txt  \
90730     0  [specif, blackonblack, homicid, complet, contr...   
616522    0      [watch, second, debat, heard, baldwin, trump]   
790246    0                         [op, trump, russian, tool]   
21463     0               [dont, quit, day, job, comedi, isnt]   
291574    0  [gtprivco, provid, financi, busi, data, major,...   

                                                      WCV  
90730   [[0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [1, 0, 0, 0, ...  
616522  [[0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0], [0, 1...  
790246  [[1, 0, 0, 0], [0, 0, 0, 1], [0, 1, 0, 0], [0,...  
21463   [[0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 1], [0, 1...  
291574  [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,...

In [203]:
testDF.WCV.iloc[0]

array([[0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [204]:
testDF.WCV.iloc[0].get_feature_names()

AttributeError: 'numpy.ndarray' object has no attribute 'get_feature_names'

In [205]:
count

CountVectorizer()

In [206]:
count.get_feature_names()

['2020',
 'beat',
 'centrist',
 'coron',
 'could',
 'decent',
 'democrat',
 'distinct',
 'effort',
 'ever',
 'hard',
 'make',
 'netunfavor',
 'polici',
 'presid',
 'privat',
 'public',
 'refrain',
 'selfproclaim',
 'starter',
 'toward',
 'unfavor',
 'who',
 'would']

In [208]:
count.fit_transform(testDF.txt.iloc[0])

<12x10 sparse matrix of type '<class 'numpy.int64'>'
	with 12 stored elements in Compressed Sparse Row format>

In [210]:
count.get_feature_names()

['blackonblack',
 'call',
 'commun',
 'complet',
 'control',
 'homicid',
 'lol',
 'problem',
 'specif',
 'violenc']