# Introduction to Numpy : An absolute beginners guide to Machine Learning and Data science -1  
https://www.youtube.com/watch?v=LPcgo-SFXWU

In [1]:
import numpy as np

In [8]:
a=[1,2,3,4,5,6,7,8,9]

In [3]:
A=np.array([1,2,3,4,5,6,7,8,9])

In [4]:
print(a)
print(A)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


Why? NumPy is fast/efficient for computation.

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
A = np.arange(1,10)
print(A)

[1 2 3 4 5 6 7 8 9]


In [9]:
A.shape

(9,)

(D,) -> Rank 1 array

In [10]:
np.arange(1,20).shape

(19,)

In [12]:
B = np.arange(1,10)
B

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
B.shape

(9,)

In [14]:
B.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
B.reshape(3,3).shape

(3, 3)

In [16]:
B.reshape(3,3).ndim

2

In [17]:
C = np.arange(1,13)
C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [18]:
C.shape

(12,)

In [20]:
C = C.reshape(4,3)
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Note: this is also a matrix

In [21]:
C.shape

(4, 3)

NP Zeros

In [22]:
np.zeros((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
#Construct an identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.eye(13).shape

(13, 13)

Slicing of a Numpy array

In [26]:
C

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [27]:
C = C.reshape(12,)
C

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Array, Vector, Matrix - sometimes used interchangeably.

In [30]:
C = np.vstack(C)
C

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

The matrix became a vector of elements.

In [31]:
C.shape

(12, 1)

In [32]:
#Identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
D = np.arange(1,10)
D

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
D = D.reshape(3,3)
D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

If you multiply an identity matrix with another matrix, you end up with the same thing that you had.

In [35]:
# perform dot product of two matrices:
M = np.dot(D,I)
M

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

Cannot multiply the vector by itself because the dimensions don't match:

In [38]:
# np.dot(C,C)

The number of columns of the first matrix should be equal to the rows of the second matrix:

In [ ]:
#multiply a 15-dimensional matrix (quickly)
# F = np.arange()

In [39]:
np.sum(M) 

45.0

Add along the columns:

In [40]:
np.sum(M, axis=0) #note: axis parameter

array([12., 15., 18.])

Add along the rows:

In [41]:
np.sum(M, axis=1)

array([ 6., 15., 24.])